<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1

instr 1 ;turned on by button event
	asig oscils 0.1, 440, 0
	outs asig, asig
endin

instr 2  ;turned on in the score
	kvalue invalue "value"  ;changes between 0 and 1000
	asig oscil 0.1, kvalue, 1
	outs asig,asig
endin

</CsInstruments>
<CsScore>
f 1 0 1024 10 1
i 2 0 3600
</CsScore>
</CsoundSynthesizer>
<bsbPanel>
 <bgcolor mode="background" >
  <r>138</r>
  <g>149</g>
  <b>156</b>
 </bgcolor>
 <bsbObject version="2" type="BSBLabel" >
  <objectName/>
  <x>107</x>
  <y>6</y>
  <width>218</width>
  <height>41</height>
  <uuid>{2cb4b857-9f1f-4eff-8058-11ce0a604257}</uuid>
  <label>Button Widget</label>
  <alignment>left</alignment>
  <font>DejaVu Sans</font>
  <fontsize>18</fontsize>
  <precision>3</precision>
  <color>
   <r>0</r>
   <g>0</g>
   <b>0</b>
  </color>
  <bgcolor mode="nobackground" >
   <r>191</r>
   <g>204</g>
   <b>234</b>
  </bgcolor>
  <bordermode>noborder</bordermode>
  <borderradius>1</borderradius>
 </bsbObject>
 <bsbObject version="2" type="BSBLabel" >
  <objectName/>
  <x>6</x>
  <y>45</y>
  <width>374</width>
  <height>66</height>
  <uuid>{a9056c84-91e8-4a49-9e7d-666460fb2b8a}</uuid>
  <label>Buttons in QuteCsound can have two purposes. They can transmit a value when they are pressed and they can generate score events in realtime when they are pressed. Their exact function depends on the type of button.</label>
  <alignment>left</alignment>
  <font>DejaVu Sans</font>
  <fontsize>8</fontsize>
  <precision>3</precision>
  <color>
   <r>0</r>
   <g>0</g>
   <b>0</b>
  </color>
  <bgcolor mode="background" >
   <r>191</r>
   <g>204</g>
   <b>234</b>
  </bgcolor>
  <bordermode>noborder</bordermode>
  <borderradius>1</borderradius>
 </bsbObject>
 <bsbObject version="2" type="BSBLabel" >
  <objectName/>
  <x>13</x>
  <y>499</y>
  <width>369</width>
  <height>74</height>
  <uuid>{a7da460d-cfe1-487c-8ec1-6fc05692d212}</uuid>
  <label>There are three other type of buttons for buttons with images. Pictevent and Pictvalue are equivalent to Event and Value buttons but display a picture. The Pict button is simply a decoration.</label>
  <alignment>left</alignment>
  <font>DejaVu Sans</font>
  <fontsize>8</fontsize>
  <precision>3</precision>
  <color>
   <r>0</r>
   <g>0</g>
   <b>0</b>
  </color>
  <bgcolor mode="background" >
   <r>191</r>
   <g>204</g>
   <b>234</b>
  </bgcolor>
  <bordermode>noborder</bordermode>
  <borderradius>1</borderradius>
 </bsbObject>
 <bsbObject version="2" type="BSBLabel" >
  <objectName/>
  <x>203</x>
  <y>118</y>
  <width>179</width>
  <height>210</height>
  <uuid>{f43311a3-c5f0-4368-925a-3ab5324658ac}</uuid>
  <label>Event buttons apart from transmitiing a different value while they are pressed can also send score events to Csound. Any valid score event can be triggered by a button but preprocessor symbols like carry are not accepted. The event generated by this button is 'i 1 0 3'. It turns on instrument 1 immediately for 3 seconds.</label>
  <alignment>left</alignment>
  <font>DejaVu Sans</font>
  <fontsize>8</fontsize>
  <precision>3</precision>
  <color>
   <r>0</r>
   <g>0</g>
   <b>0</b>
  </color>
  <bgcolor mode="background" >
   <r>191</r>
   <g>204</g>
   <b>234</b>
  </bgcolor>
  <bordermode>noborder</bordermode>
  <borderradius>1</borderradius>
 </bsbObject>
 <bsbObject version="2" type="BSBLabel" >
  <objectName/>
  <x>6</x>
  <y>117</y>
  <width>188</width>
  <height>210</height>
  <uuid>{16f25933-2318-4091-ab37-b57f1a656ab9}</uuid>
  <label>Value type buttons transmit always 0 on their channels when they are not pressed. When they are pressed they transmit the value set in the preferences. The button above transmits a value of 1000 which is used to control the frequency of instrument 2.</label>
  <alignment>left</alignment>
  <font>DejaVu Sans</font>
  <fontsize>8</fontsize>
  <precision>3</precision>
  <color>
   <r>0</r>
   <g>0</g>
   <b>0</b>
  </color>
  <bgcolor mode="background" >
   <r>191</r>
   <g>204</g>
   <b>234</b>
  </bgcolor>
  <bordermode>noborder</bordermode>
  <borderradius>1</borderradius>
 </bsbObject>
 <bsbObject version="2" type="BSBLabel" >
  <objectName/>
  <x>12</x>
  <y>470</y>
  <width>167</width>
  <height>29</height>
  <uuid>{3e9f4268-b2f7-496f-94ea-a22e8f68736c}</uuid>
  <label>Pict buttons</label>
  <alignment>left</alignment>
  <font>DejaVu Sans</font>
  <fontsize>14</fontsize>
  <precision>3</precision>
  <color>
   <r>0</r>
   <g>0</g>
   <b>0</b>
  </color>
  <bgcolor mode="nobackground" >
   <r>255</r>
   <g>255</g>
   <b>255</b>
  </bgcolor>
  <bordermode>noborder</bordermode>
  <borderradius>1</borderradius>
 </bsbObject>
 <bsbObject version="2" type="BSBLabel" >
  <objectName/>
  <x>4</x>
  <y>331</y>
  <width>377</width>
  <height>124</height>
  <uuid>{2767b528-7849-4306-85be-7b0aeeffccef}</uuid>
  <label>There are some reserved channels which can send information to QuteCsound instead of Csound. The channel '_Play' can start and stop Csound. The channel '_Stop' can start and stop Csound. The button must be of type value or pictvalue.</label>
  <alignment>left</alignment>
  <font>DejaVu Sans</font>
  <fontsize>8</fontsize>
  <precision>3</precision>
  <color>
   <r>0</r>
   <g>0</g>
   <b>0</b>
  </color>
  <bgcolor mode="background" >
   <r>191</r>
   <g>204</g>
   <b>234</b>
  </bgcolor>
  <bordermode>noborder</bordermode>
  <borderradius>1</borderradius>
 </bsbObject>
 <bsbObject version="2" type="BSBButton" >
  <objectName>value</objectName>
  <x>44</x>
  <y>290</y>
  <width>100</width>
  <height>30</height>
  <uuid>{03723e12-b763-4641-b1ab-3ffdee02428d}</uuid>
  <type>value</type>
  <value>1000.00000000</value>
  <stringvalue/>
  <text>Value</text>
  <image>/</image>
  <eventLine>i1 0 10</eventLine>
 </bsbObject>
 <bsbObject version="2" type="BSBButton" >
  <objectName>button1</objectName>
  <x>243</x>
  <y>292</y>
  <width>100</width>
  <height>30</height>
  <uuid>{e2702106-c0b8-47b9-8754-d87a2480b056}</uuid>
  <type>event</type>
  <value>1.00000000</value>
  <stringvalue/>
  <text>Event</text>
  <image>/</image>
  <eventLine>i 1 0 3</eventLine>
 </bsbObject>
 <bsbObject version="2" type="BSBButton" >
  <objectName>_Play</objectName>
  <x>256</x>
  <y>417</y>
  <width>100</width>
  <height>30</height>
  <uuid>{9a1f4b9d-3757-4fb5-b522-0b6981bb9b4d}</uuid>
  <type>value</type>
  <value>1.00000000</value>
  <stringvalue/>
  <text>Play</text>
  <image>/</image>
  <eventLine>i1 0 10</eventLine>
 </bsbObject>
 <objectName/>
 <x>682</x>
 <y>42</y>
 <width>422</width>
 <height>617</height>
 <visible>true</visible>
</bsbPanel>

<bsbPresets>
</bsbPresets>

<EventPanel name="" tempo="60.00000000" loop="8.00000000" x="0" y="0" width="596" height="322"> 








</EventPanel>