<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1

instr 1 ;turned on by button event
	asig oscils 0.1, 440, 0
	outs asig, asig
endin

instr 2  ;turned on in the score
	kvalue invalue "value"  ;changes between 0 and 1000
	asig oscil 0.1, kvalue, 1
	outs asig,asig
endin

</CsInstruments>
<CsScore>
f 1 0 1024 10 1
i 2 0 3600
</CsScore>
</CsoundSynthesizer>
<MacOptions>
Version: 3
Render: Real
Ask: Yes
Functions: ioObject
Listing: Window
WindowBounds: 740 181 422 617
CurrentView: io
IOViewEdit: On
Options: -b128 -A -s -m167 -R
</MacOptions>
<MacGUI>
ioView background {35466, 38293, 40092}
ioText {116, 6} {160, 34} label 0.000000 0.00100 "" left "DejaVu Sans" 20 {0, 0, 0} {48896, 52224, 59904} nobackground noborder Button Widget
ioText {6, 45} {374, 66} label 0.000000 0.00100 "" left "DejaVu Sans" 8 {0, 0, 0} {48896, 52224, 59904} background noborder Buttons in QuteCsound can have two purposes. They can transmit a value when they are pressed and they can generate score events in realtime when they are pressed. Their exact function depends on the type of button
ioText {13, 499} {369, 74} label 0.000000 0.00100 "" left "DejaVu Sans" 10 {0, 0, 0} {48896, 52224, 59904} background noborder There are three other type of buttons for buttons with images. Pictevent and Pictvalue are equivalent to Event and Value buttons but display a picture. The Pict button is simply a decoration.
ioText {203, 118} {179, 210} label 0.000000 0.00100 "" left "DejaVu Sans" 8 {0, 0, 0} {48896, 52224, 59904} background noborder Event buttons apart from transmitiing a different value while they are pressed can also send score events to Csound. Any valid score event can be triggered by a button but preprocessor symbols like carry are not accepted. The event generated by this button is 'i 1 0 3'. It turns on instrument 1 immediately for 3 seconds.
ioText {6, 117} {188, 210} label 0.000000 0.00100 "" left "DejaVu Sans" 8 {0, 0, 0} {48896, 52224, 59904} background noborder Value type buttons transmit always 0 on their channels when they are not pressed. When they are pressed they transmit the value set in the preferences. The button above transmits a value of 1000 which is used to control the frequency of instrument 2.
ioText {12, 470} {167, 29} label 0.000000 0.00100 "" left "DejaVu Sans" 16 {0, 0, 0} {65280, 65280, 65280} nobackground noborder Pict buttons
ioText {4, 331} {377, 124} label 0.000000 0.00100 "" left "DejaVu Sans" 8 {0, 0, 0} {48896, 52224, 59904} background noborder There are some reserved channels which can send information to QuteCsound instead of Csound. The channel '_Play' can start and stop Csound. The channel '_Stop' can start and stop Csound. The button must be of type value or pictvalue.
ioButton {44, 290} {100, 30} value 1000.000000 "value" "Value" "/" i1 0 10
ioButton {243, 292} {100, 30} event 1.000000 "button1" "Event" "/" i 1 0 3
ioButton {256, 417} {100, 30} value 1.000000 "_Play" "Play" "/" i1 0 10
</MacGUI>

